{{- if .Values.serviceAccounts.sparkoperator.create }}
# append empty namespace so a role binding to current namespace will always be created
{{- range (append .Values.rbac.additionalManagedNamespaces "") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sparkoperator.serviceAccountName" . }}
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ include "sparkoperator.name" . }}
    helm.sh/chart: {{ include "sparkoperator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
{{- end }}
