{{- if .Values.rbac.clusterResources.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-role
  labels:
    app.kubernetes.io/name: {{ include "sparkoperator.name" . }}
    helm.sh/chart: {{ include "sparkoperator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - "pods"
  verbs:
  - "*"
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - "services"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "*"
{{- end }}
{{- if and (.Values.rbac.namespaced.create) (ne .Values.sparkJobNamespace "") }}

# create a full list of managed namesapces (append current namespace with additionalManagedNamespaces)
# done this way as a workaround for the helm bug, which translates {}->{""} when passing empty list on cli
{{- $managedNamespaces := list }}
{{- if and (eq (len .Values.rbac.additionalManagedNamespaces) 1) (has "" .Values.rbac.additionalManagedNamespaces) }}
{{- $managedNamespaces = list .Release.Namespace }}
{{- else }}
{{- $managedNamespaces = append .Values.rbac.additionalManagedNamespaces .Release.Namespace }}
{{- end }}

{{- range $managedNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ include "sparkoperator.name" $ }}
    helm.sh/chart: {{ include "sparkoperator.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "spark.serviceAccountName" $ }}
  namespace: {{ $.Values.sparkJobNamespace }}
roleRef:
  kind: ClusterRole
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
