{{- if .Values.rbac.namespaced.create }}
# append empty namespace for the current namespace
{{- range (append .Values.rbac.additionalManagedNamespaces "") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mpi-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mpi-operator.name" . }}
    chart: {{ template "mpi-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
{{- end }}
