{{- if .Values.rbac.namespaced.create }}

# append empty namespace for the current namespace
{{- range (append .Values.rbac.additionalManagedNamespaces "") }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ . }}
  labels:
    app: {{ template "mpi-operator.name" . }}
    chart: {{ template "mpi-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "mpi-operator.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "mpi-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
{{- end }}

{{- end }}
