{{- if .Values.rbac.namespaced.create }}

# create a full list of managed namesapces (append current namespace with additionalManagedNamespaces)
# done this way as a workaround for the helm bug, which translates {}->{""} when passing empty list on cli
{{- $managedNamespaces := list }}
{{- if and (eq (len .Values.rbac.additionalManagedNamespaces) 1) (has "" .Values.rbac.additionalManagedNamespaces) }}
{{- $managedNamespaces = list .Release.Namespace }}
{{- else }}
{{- $managedNamespaces = append .Values.rbac.additionalManagedNamespaces .Release.Namespace }}
{{- end }}

# append empty namespace for the current namespace
{{- range $managedNamespaces }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ . }}
  labels:
    app: {{ include "mpi-operator.name" $ }}
    chart: {{ include "mpi-operator.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mpi-operator.clusterRoleName" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "mpi-operator.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
---
{{- end }}
{{- end }}
