{{- if .Values.exportCustomMetrics }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dcgm-exporter.fullname" . }}-custom-exporter-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dcgm-exporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: "dcgm-exporter"
data:
  custom-exporter-metrics.csv: |
    # Format,,
    # If line starts with a '#' it is considered a comment,,
    # DCGM FIELD, Prometheus metric type, help message

    # Utilization (the sample period varies depending on the product),,
    DCGM_FI_DEV_GPU_UTIL,      gauge, GPU utilization (in %).
    DCGM_FI_DEV_MEM_COPY_UTIL, gauge, Memory utilization (in %).

    # Power,,
    DCGM_FI_DEV_POWER_USAGE, gauge, Power draw (in W).

    # NVLink,,
    DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL, counter, Total number of NVLink bandwidth counters for all lanes

    # Temperature,,
    DCGM_FI_DEV_GPU_TEMP, gauge, GPU temperature (in C).

    # PCIE,,
    DCGM_FI_DEV_PCIE_TX_THROUGHPUT, counter, Total number of bytes transmitted through PCIe TX (in KB) via NVML.

    # Memory usage,,
    DCGM_FI_DEV_FB_FREE, gauge, Framebuffer memory free (in MiB).
    DCGM_FI_DEV_FB_USED, gauge, Framebuffer memory used (in MiB).

    # Clocks,,
    DCGM_FI_DEV_SM_CLOCK,  gauge, SM clock frequency (in MHz).
    DCGM_FI_DEV_MEM_CLOCK, gauge, Memory clock frequency (in MHz).

{{- end }}
