{{- if .Values.rbac.create -}}

# append empty namespace so a role binding to current namespace will always be created
{{- range (append .Values.rbac.additionalManagedNamespaces "") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "mlrun.api.fullname" . }}
  namespace: {{ . }}
  labels:
{{ include "mlrun.api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "mlrun.api.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "mlrun.serviceAccountName.api" . }}
---
{{- end }}

{{- end -}}
