dependencies:
- name: nuclio
  version: "0.7.8"
  repository: "https://nuclio.github.io/nuclio/charts"
- name: mlrun
  version: "0.5.11"
  repository: "https://v3io.github.io/helm-charts/stable"
- name: nfs-server-provisioner
  version: "1.1.1"
  repository: "https://kubernetes-charts.storage.googleapis.com"
- name: mpi-operator
  version: "0.2.1"
  repository: "https://v3io.github.io/helm-charts/stable"
