{{- if .Values.sshService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "shell.fullname" . }}-ssh-key
  labels:
    app: {{ template "shell.name" . }}
    chart: {{ template "shell.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  authorized_keys: {{ .Values.sshService.publicKey }}
{{- end }}