{{- if .Values.sshServer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "shell.fullname" . }}-ssh-key
  labels:
    app: {{ template "shell.name" . }}
    chart: {{ template "shell.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  authorized_keys: |-
{{ .Values.sshServer.authorizedKeys | indent 4 }}
{{- end }}
