apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "metrics-server-exporter.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "metrics-server-exporter.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "metrics-server-exporter.name" . }}-role
  apiGroup: rbac.authorization.k8s.io
