apiVersion: v1
kind: Service
metadata:
  name: {{ template "pod-gpu-metrics-exporter.fullname" . }}
  labels:
    app: {{ template "pod-gpu-metrics-exporter.name" . }}
    chart: {{ template "pod-gpu-metrics-exporter.chart" . }}
    release: {{ .Release.Name }}
spec:
  type:  "{{ .Values.service.type }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ template "pod-gpu-metrics-exporter.name" . }}
    chart: {{ template "pod-gpu-metrics-exporter.chart" . }}
    release: {{ .Release.Name }}
  sessionAffinity: None
